package org.yasar.ds.trie;

import java.util.HashSet;

// https://www.codingninjas.com/studio/problems/count-distinct-substrings_985292?utm_source=youtube&utm_medium=affiliate&utm_campaign=striver_tries_videos&leftPanelTab=0
public class Unique_Sub_String_Count {

	

	public static void main(String[] args) {
		long _millis = System.currentTimeMillis();
		System.out.println(
				countDistinctSubstrings_BruteForce("abc") + "\t" + (System.currentTimeMillis() - _millis) + "_millis");
		
		_millis = System.currentTimeMillis();
		System.out.println(countDistinctSubstrings_BruteForce("kincenvizh") + "\t"
				+ (System.currentTimeMillis() - _millis) + "_millis");

		
		System.out.println("------------------------------------------");

		_millis = System.currentTimeMillis();
		System.out.println(
				countDistinctSubstrings_Trie("abc") + "\t" + (System.currentTimeMillis() - _millis) + "_millis");

		_millis = System.currentTimeMillis();
		System.out.println(
				countDistinctSubstrings_Trie("kincenvizh") + "\t" + (System.currentTimeMillis() - _millis) + "_millis");

		_millis = System.currentTimeMillis();
		System.out.println(
				countDistinctSubstrings_Trie(Code_url) + "\t" + (System.currentTimeMillis() - _millis) + "_millis");
		
		_millis = System.currentTimeMillis();
		System.out.println(
				countDistinctSubstrings_Trie(S2) + "\t" + (System.currentTimeMillis() - _millis) + "_millis");
	}

	public static long countDistinctSubstrings_Trie(String s) {
		int n = s.length();

		// Intialize the root of the trie.
		TrieNodeOps ops = new TrieNodeOps();

		// Insert all suffixes into the trie.
		for (int i = 0; i < n; i++) {
			ops.insert(s.substring(i));
		}

		// Count the total number of nodes in the trie.
		long totalNodes = ops.fullNodeCount();

		// Return the number of distinct substrings.
		return totalNodes;
	}

	public static long countDistinctSubstrings_BruteForce(String s) {

		HashSet<String> distinctStrings = new HashSet<String>();
		distinctStrings.add(""); // including 1 empty, string

		int n = s.length();

		// Iterate through the string.
		for (int i = 0; i < n; i++) {
			// Iterate till the end.
			for (int j = i; j < n; j++) {
				// Current substring
				String temp = s.substring(i, j + 1);

				// Insert the current substring into the HashSet.
				distinctStrings.add(temp);
			}
		}

		System.out.println(distinctStrings);

		return distinctStrings.size();

	}

	static String Code_url = "https://www.codingninjas.com/studio/problems/count-distinct-substrings_985292?utm_source=youtube&utm_medium=affiliate&utm_campaign=striver_tries_videos&leftPanelTab=0";
	
	
	static String S2 = "xzmirSJfUOFagNtJdTbVUYDeEHcHLcZVzlPrGGpTVINFkIphWuZUWhhRceCtjlcbRhDzVYmuRSXWvnOvHgVJZVQLKnpYIzhyNNzcyimpVNLlDBpswxiFMMlufLMQFVVTwSQRgSJSPjKwvWkMElbemivsDanFodsBSvbgNsMdPVAlIZvVHWahUliPSLdZDyokQGqXOdTkcHKnMuNGnnXHYfPWxwxwaMrmddntiJgJkVmPPhifVqupZsifFolPWVPkDWYdmNYuvNdKxRcRiMgVhJefQulLzPRaJDsVRFSTTDKjWhzyKENRNIzpOdqEbPxgauUcHEWdPGfEPSwDbGgriUSVAiMwwkVsgiuogCOqJGeQgkAuXYxZqdGncLyzgjWoyyNKRXgoxylJGVCYNkzDDFgNSRPUHaUZEIyNYtYdtleoYtsTysiwlrERdYcCSrWVCZZHtmZJQybGVGKMUKJzoZBvGzINsyWlwsZawUDXjSExKPYrwbQolwxvIhChuwwaGLNyYUGdJUZmuXQluZsqPGpGZKyZSiwQaoflxtmdSIklrTlAXURcVYvNGOvBOMgCHSThwDPrliSOIQoUqweiPkbiiEXGxcSZwVsNPPjUKPcVGuhTNGkLHmezhqefnBZopKPvyjuvpUIzRMMKRSBaEFTBUygKFOzLLheEKeLwlyPznCAPNeFgqiVIgNGMDeeuQyDFWovgLteNPMVQdcSDGMGNRubIMiETdyBeIrmWHNuCFfjxLAPlNUCZIbPkMMnEJBxUSrVpIPUnnMUNolzeIdFAfWYGsvFIybnrcUSMjmgNnZJJdwUJxdGDTUetarkISxbyzRPTxNRtcqTtqhCfEIOmPsBdYIbqtvfCgfagRVgVFkZwtMrORwRsQoTdJZchqpefWIXzqPrZBHrChWDfInljBbmAineBSRJKrIcxXByYWWNYQxAlBrnJNgmkNOPPPNbqmMWLQjygamjGeRPkKxRlYupSiyWoYehHHUpZbbXgVwCQQGnXvOxypmsCKwAQdMkSqujaRPmqktXUuWxHuUUeYcxDumIIYeQFblBqNwZIcHfxicfLRcBYOGqMfAikGoTXoeLMVplrVAKWGJMksTVnyNGsfchiYFuaIwyzAdrYBBPtIxEZYsGraNpUxMRqvpCQsgrQZIErlURDqslZndxKYaKOQKSOfdSIGeacyioXspllmSOhbARqoilwPxeujmOPbGzimsUrnenCbwwPDnCwTAjWNHmOtpGrJtRNZwgaxpRHPxVVBCwVLwrouLABDVBdQjEbSSiNhujUJIEiwTnBSuHyeQTbARpXRFiJfJLVXHaaRjfqeiPXzMltWCmNLitQacVCeHWbZUiyaSKOFHkjVzzVhFQTVRbkNCrHZXGUOcanqKySPUzDVNRsvmFTDkXPgiLozYxwRtJRgGyEVIkDUvStHiPUBRdKVdfAjhFekrjBvQZBDaTjYMXxLCfWGWWWTOoUamHFgXegXNnmwLUaclmvhdQaJJefMytcbUjnRRSjcSGssNbZypuCMRUAseqtRbiFVwAZLivHILyXUZkjxKvXddivyWqugIIPLzYYUovWHxvrhJYqTUFqTpDklQOPJdokHdzKYdJUVhCoFzwcHLNHwgMSYOuDyFTPZngJiNSANtjGSeCjzUKlVoEsnspCUrtBebmRchrCZhbBoReWWtrfanExqrRXbBAdqOgQqVDwYOBgBIhPPGpIMiebicLLDrJLOuBqOvDSjYWTsWWdaOvKQvhkTVYVqVypFzrOmQwrwfsBzzfmYHgCLNywXaNMbVIpgpaChyJaaGOEcyxOhagLgEGUEkksDtoxKqEXzbYzZTuBhlUmVPsJpuYYcHdfqaqqVssfMEXkCDllzbetOiXJwnaUkaxEHVHxgFxZKbrabFRGfbZUCczwfPYgVFNKESBpwpiLYVYxhaQsnveVAWEzOyoMsDHjEOFodIdygjnVCqmkuTNvFukMDVUILrAwmQBpKXThDDPZrwQylsbNPwVjBLYPXlTFFKGeBvlVbSqoOZFkBOCmCHPFIuqPIdQDFCLKxhUxPpybvGSNKtETlAbKiNqtwjdoUTetNNWvaectrJFOPSqSaikLVVaCoXJXUlZQNRqjEZheVxNVnSwSbVbsrLxZKqlKAkITNTpFTXQzwnOGWkOaqhwMxjlSBoxEUGmvnercTDNXKbZGHyDTedwwZiyijevbxHXuGCPqFWglajUJoTRWVhBqBaEDpoCBelpyBFgfXTtirIpNFGTQoprtUpbcsHCoZWRwolqIFubfXodTExwZPNlXrshcpZQzUqWfPmZKSqwoxLzqtdCWefuGLZcwgSNVhzeNDksVLfneFwDByDpwvhqJWqECEaWjteqyIrfinNGaLUbLgSCSwkdGpDmVdRuCAbncxrJpeguwmzXGZFNvadnCUjmINYrpLdhobatXePOpOadfqQpygGxSNRRRRTONkhQacWdajTJamSZhZZAlQeQtiMoEQLOTyPYxQrftzjFSujHwFvdNFRikMzPnpcqAVdfKLMcFymgCHklxoNMcjvYJheoDSFbYZyolNweZTbOjpTvJqtUgtQTbBwCSDACrEMDwaYwblwrLjkHjmmeUQUowOBbDRoiONLgGSgJDUOlNesTktYCnGriGWLpZbceraNVobAZuChknBbWZTiSAJklwbDASpPrgsSoqxnzutQXezuXyCedJbZCpFYVwyUmGdntXppMHLFXEYfCBWVRefMOHiKIVKnZQyVsgFuvbtenNIiBfmgRSeJqCLKbhtayqSZTuWmWAsOEckEYUyuQpyqCfDzGoOoEAROtzQEqjNlQVWQPjqeIVpZFHeRgEvnryYHfDtssTQEIYQCKYeCksCWgPfxtvHxTwvnRODPXTdgPSNDQWaCTyOrqXSDOHbgGnIwEQFaURPNaspmwsPoYtFibMOrLLDaYphAKmgMuizfJFEyHaLGhfdZFjIYAUmrpUQtURyVbxRggWAOnfrozhCibsJyoAhKffHvrApvqfChyCxoViImvmJqYRcElBuFlNgDPEcPIPnGaGtgfxboDcjxhHQmZBlNSABmoSOjBcWdxGwsFkevQLbSKConSQYHvWbwXXmXPeFPIYRWBYHzFGLFJzqZNlPzKvmLWGngNgLdteyRkCAnDwMLGyvGzGGqbjVlLzQkxbTqLIoEunUNFPMFpCSEERMRHRShuLuoBsSdiFVzrhYfWvoYSOXxgZmWwkexPFwWNWthWypPtdcCyJfQHJSeFwGfLnRhzfTMHAtXrVUHdmMEZhEAHtkkWlzTyBBIIXbcaoULcBVTynTnhsSjlyiCPkrEpMKbMhHengGOHjMkHdyydXKgnbqxjxGjQhyPKFUDDVprjkZsTnKRaqPmeNLpYtlOCiSydLWVXnbwrhLQrFUjwjTYqXLNuSRapRPjyIqiEvfhLbBBMrkPsxAfVvtKoRXxckPLeunVHchhSaQKTGXBipSHPaExwBqOBVFaifmFKanYXAkGICaUegKKQObGImwDfkGObIewxfNWtDOmfNUTLpkqiWkFKptrxejvdYqlqsJIBGUMNTamcQZCUuDAwKstPgRRSSAQHnYkJRcXWYVIXDuipvzvMXifVTjBftBmLaJBudOyKKpmmCnimZcUtDmqtRDuHzRpkDvqwOQPkYtDkLopceUsjQZkIcLTAmdrGoAdJHkUnoOLQwuuyNNvhoQfBESeTOTZQQgMSYNpeHGgppqfhSMcCQlYWLqRyfkVKRONjmtDZHtajUgUydiZaiCVdCgbnegMTKnRPeaVKkgwMcmXBFPbpCXEdwPGMBYkVOThOSqADUKaIPConpIzytslJcmbKDlztdbMLSnGVZkHYTWFqeKJvbBbvMpUVzuSQUfCNDeGPYzZrXERjkhGspKtMSxMnMpvVhrUhNxpTsILQVLxeAjjpLWWDRjTuFGCgfxyOAwGdYBxUKCmTgUSBXRIilBlcJkABPTCEbSBWfhkLfTiaZtzAFmCSmvtczaSgNWVdQVVDFChFJZThLUMOiOzRDxazSVFgBoUivPNrVarUehaIJpWzHWJZRyluYhOXlSklmNoiHXdJPecJXPkKSNSugjnnnAahGvrdpKgHXRolILbhkTZPyzgIqvqqaICBCNpGrwnYNaWdoukNdGgxjPuujdhdNxOAALgxeWudnrMAhCnfdrKJHTMJFhmsOLESPXmIfhyIiQtvxtASmcqBfSuMuZgDfdYlkAAQRMWdvmnJqjKoLHNjLuSzNXwCiqzWJFLpYFZMTTJiUbykOcrYAhaKwWVPTOPIGQrtANxNMKqXRaQFKZhLncoppWIiAFgkuwqwRbstZjkvIDLKXRHtYrXfMBsXHGOeoCFXMdHBPoDvXqVRLYGBTyxLkJrShliVobSGypCassbckSObWejOQrwSYtJWKBdFiLEfoyrHklYywdWfSUPKNXFKYJSnYWYWFlyhPWzLlsWLKvfYtkglBKTkAVdVgwSMknaLVixldxgElCdDJKiopVJxeYNqYyLeIqychkhXhFGRaZjFhZDrfBPoLkGuAmjDsLKCJjjmNRvYOdPzjXZLUuERZvifUBYcfWBOiucxjVXlSkqkgEnAwHLBUWOezcefrXOlxnwJdyAHreeOOgNntsuSQuAYjIjWGLBUknGMtvoJHppvLshxGtlszLkrfPZzlChzxFFtALWoLlTZZrcXFFeZvHYcEkgNfnFDwQvvvIJHjQUdqzoAoeTfJZkJecvzLYpTAdOAqAwBqERpyRYOnZkhgidgtCwHFmsJqdEQgaAolNPggjvmBfUxrSQhIEEgmBtfCMXfPfqAbcNKhDGiREFGTXokkWHGJsTKPcFBiQHYVPvRLLVEXwWARVbaMqEuZmbeQURiXYmQkqJPYeLINGKEyOPygTbopnsnQJLOttwjfuSBQrCYFxqhWSwreNNyYYpaXjLRRxpLIwnUigtGilLqhLPdGKYYSIiSgCFgaBKnCyhXhgCRluJYMitGFQakedAhEgbYsnVclMpwkPxBNBqydzLXCewuESXcGlyqcEzfomOjBKYsYGpcbprYWAmvXrDXvTcbMMeyCbGuPUPUFKkcTDOWrISUMjITFCKKQaJVpjLeBzwZcRXoAALJRRmhycswJfEOBLEyoMtHWTrmZJnhBapeDKdvJHelGUKwpaCsDSAcuuKOXpdFuVpjDyTKxfSinQuvFMtqWCAjoXMsKnHAWJHTJUFhcqkWsHomkXUXNAmUYpUMKPlAvkySAYAAuHtRBCtNqdujXkyvEQEQNSwLzRnmvZsaJPBYFYuAJCEzNmcliYfepiFLDgrmNiAwwrBPpZSmCeuZTWzAeNyXkKBsAbEZIURjbFHPXSkXjUnmoSGwvtCtwICUwkMQuTGFSbMEbkhxRYqYdAWDhdnPLGYvbyVxAHGAPtwBQrcSlQVocljIDwHGDLwRUaQziOOQSnriRpLuZAGZBYQBBsYwsnRZwejYXXebXhVUzOXOMNFYCSMkcmELFeysnjXTdWpaVOkhMVSSnUsJEoYojhfavdvnPAzPLlzqGDmlVcHGggzIELEfXJEKmBMPRsmlsyxAzfbhNYxZEjAFgGxbhPCVgOzKdbQyGKoPpFOWkIGBsQNLeKFuiLQaGeULTgJvGYPTbddYPRwovVbusYgSXpbFahQHHWPqyzzKIGbwWVTFksJbJExETNafFRCteEHqEZMXsvQSzFuIpZMGPYXYPyJlCZBUOYhsTPjGSrhtTfJzCDRiappEoNkilOfJZmNKIMBRlRfFTnzAVmrNbiNGUlOfXOsVktQDBJZpVSZXByRQEcEdEVNigCaYLACYSBKKksmLhXQBrmPrjyGiGJrphGxyqabrAgkTOKyAMJJsVXwRcoNrecGowrpQLlaRAqSdFUUACwUyjmEgFrBXqSfBTVRXCLHFaBeozaxlWUMaFkDlaUGMeVdcWNECBUihSelUoShofdmZryKJueSvrOwQGfSEiidPtzmrKjbeuxrhVGTxrPRdsnXeOKMQxgIUEYOItPYAhkxhHzajpKEhPlxTIugfHnsFlQjsZJfJHNsJkOGnoaRCzOCWFWZhJMUOIHMxtePNUEkDvbOLdiUedFknqFpJDjnmhhwPeAVKapLcZiHmMIimYLarNzRktoswqCzBSalVfCdKyttXNCTdnCoqAyaRXixxKPIZTKsfcFgvFkwBpQVVYdKMczWDIgakJKOpGHJjqLKNpznsGbxBzkwuoIORozSHOSTznaZtfofIiXbdhGwcCBlJkDyVFmhlSvqZFnAtRoXEcJwcmLvIBcIXwVILfpDZYKjetXysfjaggfKPkFiPoiXReWaUzfUkLgsuLXCTbFMyGIOuYUhYymojrfHcehHbaTtvXOkfwHojMlEkiqztipVjVxmteMEhgmmtclxbkbriGICdsQeAOuyouVUfBEEBadDYZGiyRFcaxasQCTIMdVtIHlhRsLRvPqaLnxqIrgWhRgEmIADUPQqjADbhKKqVQuBWziIARmIMxOqoGKRusoYHuGQLKZMuAKJTYhHuaIYxPNoRwrKjrVaNuiEZqDIpxsiJbJObrvllHLHhwyyfuCOBhIjVKCGFNvkVyaSzIkRScaxxBLemoxJuENRKvrgOstGTEmyfgGzfTFcbxFjnpOeFuZiaYybfRVAkaygXAhyGYfYQRVKelabyIAKQvEDUVnAZXMoBtSECvcSDPoFlRsDFVXSaPjbRqRUjBfGtYUfAnJOIUnzmuwnroyLfYHdZvwNFALeewtWJOypjrKwNHDeEeCBrWsOgGoVHkHbKMlgLesRxlYnIKNTbXsRICATIozcostAKgTkaePJMRHiasLrQpJKeoOzddzEjofhqPVnVQBgIOmvAyUopLhRYmxdlXSYkhrSuyHBEQqcbAsYNvTYISFNcKfilvGQdwxNokckdAbkfuzRlUWmebkxlIxuvbhmsAESnJQGrkkwCiWpJfvMwGtwwRduLcefKjgFiHlEVlnwuLCHrCODavABKFpBejZJpJLCSulXaSBFQADMNUdslPMxSlgApSawNYJsZPCbuVDmDMKDXiGMHepuAqMBUzsLyQsZtbrNCMaQETFgZHLRzybwtfLgFMxcQeduqRgVwkZuTUNjQgDZrrFeQaQKdcZomIcGzQrXtGlLzJGoUXLiKyvWRfNlkJGtOdQJimFVikRSpRlxonSgEAYdJcvBwqIZLsErsBXurHSbSRWqLmerJYKHURuTwTJWdWyYoSqFuavdGPcIlpupftwWDOiehTLqfscEGngRfLnBtPJXKNzcnnDHruuRehxpslwpMVveHcnldbzmWTeIdMvOqjOEMVfFeNiXrOvyJZymqIoXDOLaeNdfYmviOXazvnbXEeuhvsCHNxxYofboPTmiaZoJKHHcwgmZbQfcclJzppgZJywMQtGDFLOeHwzDyZIhMOKEMEzqmJvEWsJjSIiUgGggdOEQXeXdffjVyPxdVjoAgZshMhgqghaIIwztRszVOIUarkgfmHnSdspFlazrXYfWqIKSeInfcchiHYIGaLClmBnsMTdkSnoDGcaNydTvjBbPOggRnzGetOdNAmXLDFafgpIBLedIShnLxllkJlyGRmgllqFDzLvfsyfbwXvSThQPCRsbqpiQbjnDfnIltsLPMwZZzcEwOERoiROMtEfQNbrEhGCXxopqsVjKeCZeGevVfxeflvTFmzNaEjmXNcQOYJFfdSByOVhAIWGgpmQAxuaRykhZeFveFigDmeMvrDkeXgpElcLMgacCdImLejhJJlMFPFWwZzvQQdJICeptoxATlaHlTHRHNakYLeVdozTDfyYafIXytKRNJeLIyIgVtBRskSSiquCRFRTPwjYGFihnjseqElLRcAtYbmgxCBncLQLsyKxOfGcSivFNFfLnPeOkPzBPMDKDJtcwNILoXJsrEtOraivwlDkeNLVcImkXRLNDaUJZfwNelgzlyJTRIavrbAajpszVJsGutxtfBWQIcsDZNGEHfGJmcscVpHTRbdOmrQCaznpfKCqzBgSgbWSGvfEwhrtvNIdheJOfQpJyAhApzMCCheRGfGghQuNRTdmzouUidOmwWUCCjMpRCKBJBALpGEazBApZfasvknaWlYSfjYUzPUKUyBaMDUylcVuBVMDmryQfNqBQziRsunjagGPdPSfXuBQRsYKHEQkpReWbXAlmJKgHmRttbGlqdTdLvvGeGtGkmUNKHXESUxiGzkbMhcafRdCblIeqGWBAWpIswhgfuUgRPtoFaEvqwBnYFyqHUSxiudYqvqZpTzhWQeXTEKbYAxCPlmlpJzzOoppYLpjpRXVXFwdYDnExHIVchXXItJnnZXbwOPQkXdqunxarsOYKIcadWVFMRCMhwcGSkzFkkerpfmMAaQYJSysAhfpRxQVdbqIrkZUPUEBvfpidWXazsuzpsYTtPHBqcuXqAPwGJsXtDDcLFvcKqiUDduCeQqnOwavRNqXGDohLwCIspANZisgoHFgrNbrkNUbxvKuvEaWNUmsepXEzKnFeHqjwjuYYWwFaATnhxqQatASOntqltfqyYftMpCeeikocDupOPviJFSPwOgerKTBbKuGdyIVCksJrluFSUzRDMYczTZZJswxZdeZufZheOtGFKiCyydXykpnBTQdtwkiVtQyvAmoUdUJyTxOwdjFaAGimcAPiFuUYpDlYkhbaTuywxAQowmQORbRifIOiOuNXyxXKArIDmYLerlYQlbXMjOyFJXvwNpzfDfwPxSjhwDpFRiCLtOIFIVZSWYzzDmVIZyBBmjYfjabZHgrmhCZXvXRtBJkxquTtwTkKAYHPmBKedZJEWUhZlnrMsdWrqvOcbWvLGVJyOmEfFJauTgGmKkixQWkqXGVeSUtnZPoBRDqhbzlvjCRHfosoeQsbbjOQdLguSDvcLxoYrlxetqRTCSShxTgZCOYJKYHKMyVNbMgWMgyFLsZVfEevcGwWPzelrvJVZPeKtqjThJMVFIKhjCgzjXmBCePFWjEkJgZaXdTjQaSigNiTcYUgOrkLZMrYRdGWiqkSqHgzzgDxEnyzIkRfipyDZZNpGCcwPQMWkfYLFrcWsFcCLHUIkUPiHhQUkVttBAGVNpEyTCEenwqFiMefUlTSUIRvhDdyZXWzkJaJhnATAftgLjLehNYIEkNskZCXJTTICyOnIdOHoAOspEIHZUwgYQFcRQpOFZdeNbBiKvmHGisxsxUgfiQDWEzvVioElcGWbPgJRNnFteLlbHaMrAHUwlAKHAGNTqCItXkkpgyZoEKndPbikSwhOoVZWmtXngzotOIpfujncnTkmvgGDYXmyQeJSzgxjBObqYtPAmDRBCGGPztGJCMkpWdwvUaGCjmBBdghndwUkRNUoYeDTFgDTTciCwnUpHVoUlIOFevnpdJIhKSFaUTeNuZpzhSykFKkZryNninDqkpvLVsQAUWpfeEWoSpzWEYBQoyPNwGUXPHJfXhHevgNeRIkPdGrTIYVxvGYeJVcFOBRSXKrCzzDtOukUusiVbyqLippUNNzqqKytNkoMcLIMYUDDlfLgbiutHZthjxNMnvyiScXbMJRIgXbsxhRwQFLWuvlXVXXCNoWbpsyuWPCPDDhJEcFWgEhNbbksBBMMnVbibtmsjVVVGmHOStIUgvCkdQgwfklGGlJOLBadnHmFTUwSpfsZqSHneIqqMpvRiKkjqyLqYNATMfBWatnvgJhQLYeEFRjwhnydBRHDIVejunbdjoagaiCwQkaSlLJRPnvcTALBbFwCJSSpdHgZcwchPncBgNFndcUroVndRkoBUJuVoCMDRCycylvCZJYjGBukNILbqnsUTvrmIxmtbjkTrCDFNnkCLmseJixrxatJOEBVjgMjozOvIUYQkEureHGKhvoUSkOslrkvFHUGiweGDtckUBWbMnKHZClFrLsjEllETKXVPEqGJDLtNzwUFaJmYFbjVhlwBVOjPPFKeDPcIFwQjMVrlFKjPDFHIiSTXVAsoGARgBLZyUpUjxPbfUtuCxLKTfxDASWYSHRRMTKdEsuMEPveAhQBBvgmPlsrVAvbemuuWEtJijHWtvoOtVRWtEaYwTbbuCeBmdyjhaPpOcXhzccfuvZTwtnbQsThQfThRqZQJwLoCBtADgjKvuQsASMxUWYpsMtIYMdDsLwRsOGLEdPARgEIPdhkBbyjroXzRIDbYAcCCgdoZMYTEJOWHuaiDBwHmlXxsINzHqYJbNVOHVtGcxMHKSvbIteglYqsWSfMuLcNefpAAVKLwDgCnWbsEKVSOOsDNYoXpYMLflRshcLBFoCXDYlkAtzFhIEmUSMOJjmUTxgfkNAdxKbquZDESIGfsQCaEvUToiWJDjYpxZyHtNBgIxJntzvpyUhEUJBgAcCvalXcmOiAdzQFiQYyiRFNxXGLBcdFTPwysjngzdyXGwlTsNXoCLehlhnudGmMNbNwTyOpKJqXIvnYFElcDQBeponAUHVoRacSNDUXCSKUxIpcdXauOredERmESDPUSYaxWcfSPRzGiIJfPRwyXethufthRawNKOmsRnrPfNewyokWGbuVYgzHiNywINzaNliAkOdNgPdVRrZQkWaqglguvXNfYCZhnsjWymMxkFtCaENKqCQhGOMNpKHKpcVyGYRcEwtRjePoybXnTuprSzICUztWqiPYcOyOnPyZEGZuxtbqiQHPJBWgpTVCBZXVSEOTWWwjpJQdutvKYMdWSaOWcPYXEXrZsePRqaccsXyWUsuQqXSVTKKCuWFjGeYSpTONtEypGAipoKCOYpaMjeKvqCVzLJsBxmzpqhOufahoijabhzDGoGWOjcRGSDAjIMXqSuZMXmTBiluKEbstQgofZBQBFKClAtpBZhRTHuZUrsmJMdZpOYKNtqiQUpWGotRJPqzzyGShmUMnMUJkEVVSIjRWIcmMwQaCnpaLeuVJAWhAjODfSLIURIWfjYGZaRCjYdZFQkqTJAATobFNLTQZNaIDqhishKYGFCefYHVMydWhdFOvAOTqBETmxfWewgRKtTJEAlvETgftdeofTXccFAnIWNYhsYdRqyUbIVRYEZTzHLPmMwElwfEiMcugqybNCqalDbUgobfqArazNxVxMNSKFmgNPVqkhoarrTWgoHfrcFVRgSMEppQHENLUwcrDGzbaWxsXyMKscPeljJrdLkXCxqGtTGPNsoUBQsHMHmjUtsHMbSIMMzJIMKvREkIAcLelYLBfFIjvaAUKboyFzxUjUrvzCdsoPfGAqlrGebsFwZejuZgLiorcdOAFoxlMyLzJFTpHQUHxDgeWXEsBmDRcqNaPRaZgOiCuqaCRcTcSPeiejHGrxiPuXrxyKoQwjEWiSnmmrWgXRiSYJirkDtWjyPaYrVSoXQkrXjAQcoZZNxysgAupQdOffFbGivSmVngQfcKfGfXHKTCdfCuLjLdIJMabqEvAsxoNyqcOSmCslDQuDRzgYXiqSyXEzALFoRCXvHvTViiGGuoWRxEfQpoikyxOcozpAgSzoAKPIlHLlENKCqHJpObGsLrcbDNMWZzaokMHbsudfDptQBoPfPqbBAoRcUxvAcSklJLZTohARNONdBvkasFeRZokqSkVGYOtHYdlxviHFTEJdIojaTsiVptyyBYHGncfunkqTfYXHjRpakxgWVHuJlMhqjuaHmwGkUGPKsGghFMwyFOPEkpGhRaPYiuJpqxNoTiqIoUdsPsodfDVaGdUKbKsTPxLfLYBkWrcZahfYwGdqfmtsEfLIoQmuzYjZNlALVUCjIKcEpIeevbVORWdArzJYllglCXcPqVKZSAnRtjiJavKRpHMeXjjJfLJuRbwzhFQaWiuzymQnHqRaGdIHjSEyoOKfhTTQkheoIkuoToFzpeoXWFzvVUZxQIiYEKsNHDGJdWuOrCRnlpcRwBhpOGRnaMZffFxcxvgtdPgrtUdQotoKZYYkwxKZwjeazdPLQwAmrQJgDQRALhJohpANHzdgFcOtLCUzXJiGShWANpMfeYGeYAFsXGUPRkcMPWHDIFsNQdqGjtHKzFrxfXEWsEnekvGNURPKMfwBzmfRHsCFzSoYXejuLLueMkEXcpOrpxxIeLecTpeYpFOxSMGZdNSfnLHqPEASqlAJwDhwVIsmcYlEkWzfjyFkkoDdGPpVCVxVJFCQZpbSLmLNXNLkMYlntSyxOiDqklRgRaBAKsGHSTsvOTRIatkYWSJlaMcigpDLWhoXRrrpKoDpcpyVSCsTXAxcRPUpFDpRTqgmbMFbmHcXVGdIhRqmQDZwhlcjwujioZLJLkybKTpAYhUjUVxKlrNTWkVTeUtYpVcfKuTzCtVScwDkMbZuFiXglNeFPqICSqLQvwPFrWopRoOceQwbaZGmQocZZkilpYwbweWtpEUCYbcnsJMJYbzcZGuvOgCJpUBzlRfpIYJJNbutGoMotWeaiKAAeASakgPuWJYgzsIWxTOVtIGWDDYtpgFGqWKvxwIrGTkANmNiJjpbhiraaiFcsVfLkcfRmAhuflEZgoDCljMWYhpZkLYvcqCDraEpTvFZXNdcWfyvcaJMQGyntjDsggLFRMSdCwTqbEDmJDCtOVjiEQiimfstBZtGoYxQyqGaqLuJuJLfAZwxJiUJLBaJnZdPjHFasYEXDwXQdEXkwGaYQpMpRiJzyiamFxZItuXIbJGpThzLaSpuxscexioqqDDyWhSaAPpDhtPGFqIXluXSskeTeYJfZDACyZrAFDADgUbVkRWZNLLMMHVwgeMiKhiBdDZEODhNinQDAPELdgrnCiuPDzcxcyAb";
}
